### ISSUE TITLE
Bug: changing the interval doesn't take effect

### ISSUE THREAD

**Issue by weitzhandler** [vercellone/tfsautoshelve#20]
Hi,

I changed the interval to 30 minutes but it took no effect and the auto-shelve keeps on shelving each 5 minutes.

**Comment by kwhitefoot** [comment]
Same here.

**Comment by vercellone** [comment]
Does the interval change if you restart Visual Studio?

**Comment by kwhitefoot** [comment]
Yes.

On 9 Mar 2018 2:46 pm, "Jason Vercellone" <notifications@github.com<mailto:notifications@github.com>> wrote:

Does the interval change if you restart Visual Studio?

**Comment by vercellone** [comment]
OK.  That is the workaround.

As for the root cause...There is an event handler which is supposed to trigger reloading the configuration based on the options form entry.  It may have been a glitch where the event didn't fire for reasons unknown, or it might be that the event is not wired up correctly.  Can you tell me which version of Visual Studio, so that I can inspect the code in the appropriate branch?

**Comment by kwhitefoot** [comment]
Community 2017 Version 15.5.6, framework 4.7.02556.  TFS Autoshelve 6.2
installed via Visual Studio.

Personally I'm happy with the workaround.

But there is another problem.  The output pane shows that lots of files are
being shelved but when I look at the shelve set I don't see all of them.
Not sure if this is a bug or a misunderstanding on my part.

Kevin

**Comment by vercellone** [comment]
Thanks.  That'd be the current master branch.  I'll take a look at the event registration code.

Do you have multiple workspaces? If so, make sure your shelveset name includes {0} as a placeholder for the workspace name, else you'll end up with 1 shelveset with changes from the last workspace to get shelved.

**Comment by kwhitefoot** [comment]
Just for completion's sake; I think i must have misunderstood how it works becuse now that I have added the date to the shelveset name I can see more files in the shelvesets.

Anyway, thanks for a useful tool.
